### ISSUE TITLE
Circulating supply calculation

### ISSUE THREAD

**Issue by Galadrin** [chain4energy/c4e-chain#19]
Hi, 
For our [information board](https://chain-monitor.cros-nest.com/d/Cros-nest/block-chains?orgId=1&var-chain_id=perun-1), we are providing a value of circulating supply that match the following formula

total_supply = https://lcd.c4e.io/cosmos/bank/v1beta1/supply/uc4e
community_pool = https://lcd.c4e.io/cosmos/distribution/v1beta1/community_pool
vested = https://lcd.c4e.io/c4e/vesting/v1beta1/summary => info vesting_all_amount
excluded_wallet = N/A
bonded_tokens = https://lcd.c4e.io/cosmos/staking/v1beta1/pool => info bonded_tokens

`circulating supply = total_supply - (community_pool + vested + excluded_wallet + bonded_tokens)`

`circulating_supply = 400895315931997 - (100000000061466 + 149395780000000 + 0 + 93038535577160)

`circulating_supply = 400895315931997 - 342434315638626 = 58461000293371 = 58 461 000.293371 $C4E`

The C4E dashboard advertise about a circulating supply = 11 308 199.9370 $C4E

can you provide the math behind this value ?

**Comment by dawid-kruk** [comment]
Hi, 
our team has prepared a new API that allows you to read the values of circulating supply and APR [api-url](https://lcd-testnet.c4e.io/). Currently, the API is available on the testnet, and with the update to version v1.2.0, the API will also be available on the mainnet lcd.

[Circulating supply testnet endpoint](https://lcd-testnet.c4e.io/#/Query/get_c4e_general_v1beta1_circulatingSupply)
The formula for calculating circulating supply on the C4E network is as follows:
_circulatingSupply = totalSupply- stakingPool.BondedTokens - stakingPool.NotBondedTokens - strategicReservePoolUnbonded - airdropPool - lockedVesting - communityPool_

Where:
- totalSupply: Total supply of tokens in the network. [Mainnet endpoint](https://lcd.c4e.io/cosmos/bank/v1beta1/supply/uc4e)
- stakingPool: The staking pool represents the total number of C4E coins that are currently being staked. It contains bonded and unbonded tokens. [Mainnet endpoint](https://lcd.c4e.io/cosmos/staking/v1beta1/pool)
- strategicReservePoolUnbonded: Unbonded tokens in the strategic reserve pool. [Mainnet endpoint](https://lcd.c4e.io/cosmos/bank/v1beta1/balances/c4e1hcfjejmxzl8d95xka5j8cjegmf32u2lee3q422/by_denom?denom=uc4e)
- airdropPool: Tokens in the airdrop pool. [Mainnet endpoint](https://lcd.c4e.io/cosmos/bank/v1beta1/balances/c4e1dutmadwfernuzmzk8ndtfah254yhrnv34y68ts/by_denom?denom=uc4e)
- lockedVesting: Locked tokens in vesting accounts and pools. To calculate the lockedVesting use [this endpoint](https://lcd.c4e.io/c4e/vesting/v1beta1/genesis_summary) and then subtract delegatedVestingAmount from vestingAllAmount.
- communityPool: Tokens in the community pool. [Mainnet endpoint](https://lcd.c4e.io/cosmos/distribution/v1beta1/community_pool)

[Apr testnet endpoint](https://lcd-testnet.c4e.io/#/Query/get_c4e_general_v1beta1_apr)
The formula for calculating APR on the C4E network is as follows:
_APR = inflation * (totalSupply / stakingPool) * shareParameter_

Where: 
- inflation: The inflation rate is the rate at which the supply of C4E coins increases over time, as determined by network consensus. [Mainnet endpoint](https://lcd.c4e.io/c4e/minter/v1beta1/inflation)
- totalSupply: The total supply is the amount of all tokens existing on the C4E network. [Mainnet endpoint](https://lcd.c4e.io/cosmos/bank/v1beta1/supply/uc4e)
- stakingPool: The staking pool represents the total number of C4E coins that are currently being staked. [Mainnet endpoint](https://lcd.c4e.io/cosmos/staking/v1beta1/pool)
- shareParameter: The share parameter is a value between 0 and 1 that denotes the percentage of total inflation and fees distributed among stakers. To get the share parameter, use [this endpoint](https://lcd.c4e.io/c4e/distributor/v1beta1/params) to get a list of all subdistributors and then find a subdistributor with the name "inflation_and_fee_distributor" in the list. The next step will be to calculate the shareParameter as follows: from the number 1, subtract the burn share of the previously found subdistributor and the sum of all destination shares of this subdistributor.
