### ISSUE TITLE
Bad completion binary name

### ISSUE THREAD

**Issue by martinkonecny** [chain4energy/c4e-chain#5]
There is an issue where binary is compiled as **c4ed**, but completion for bash is created for **c4e-chaind** binary name. The same is for default c4e directory - binary was built with .c4e-chain default directory, but it should be .c4e ?

So, if you want to use auto completion in bash, you have to use c4e-chaind instead of c4ed .

Example for c4e-chaind completion usage:
user@localhost:~$ c4e-chaind
add-genesis-account  config               export               help                 keys                 query                start                tendermint           validate-genesis
collect-gentxs       debug                gentx                init                 migrate              rollback             status               tx                   version

Example of c4ed completion usage:
user@localhost:~/.c4e-chain/config$ c4ed
addrbook.json                           genesis.json                    ....

**Comment by dawid-kruk** [comment]
According to the cosmos sdk documentation to add completion to c4ed app run the following commands:

```
c4ed completion > c4ed_completion
```

If you want to generate Zsh completion scripts run the following command:
```
c4ed completion --zsh > c4ed_completion
```

On most UNIX systems, such scripts may be loaded in .bashrc or .bash_profile to enable Bash autocompletion:

```
echo '. c4ed_completion' >> ~/.bashrc
```
And then restart bashrc file

`. ~/.bashrc`

**Comment by martinkonecny** [comment]
Thank you for comment Dawid. As you see in examples I posted, I have bash completion setted properly. I created bash completion by "c4ed completion", but bash completion generated by that worked for "c4e-chaind" command, not for "c4ed".  But it seems this issue was solved in newer version. Thank you.
